# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           /:year/:month/:day/:title.html
plugins: [jekyll-paginate]

# Setup
title:               Nick Xie
tagline:             'nickxie.github.io'
description:         'My blog'
url:                 ''
baseurl:             '/blog'
paginate:            4
future: true

# About/contact
author:
  name:              ''
  url:               ''
  email:             ''

# Custom vars
version:             1.0.0

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      unlisted: "false"
